name: Auto Create PR from Dev to Main

on:
  push:
    branches:
      - dev

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ github.token }}
          COMMIT_SHA: ${{ github.sha }}
          COMMIT_AUTHOR: ${{ github.actor }}
          REPO: ${{ github.repository }}
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          EXISTING_PR=$(gh pr list --repo "$REPO" --head dev --base main --state open --json number --jq '.[0].number // empty')
          
          if [ -n "$EXISTING_PR" ]; then
            echo "Pull request already exists: #$EXISTING_PR"
            exit 0
          fi
          
          gh pr create --repo "$REPO" --base main --head dev --title "Auto PR: $COMMIT_MSG" --body "Automated PR from dev to main. Commit: $COMMIT_SHA by $COMMIT_AUTHOR. Message: $COMMIT_MSG" --label "automated-pr"
          
          echo "Pull request created successfully!"
