name: Auto Create PR from Dev to Main

on:
  push:
    branches:
      - dev

permissions:
  contents: read
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ github.token }}
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          # Check if a PR already exists
          EXISTING_PR=$(gh pr list --head dev --base main --state open --json number -q '.[0].number')
          
          if [ ! -z "$EXISTING_PR" ]; then
            echo "PR already exists: #$EXISTING_PR"
            exit 0
          fi
          
          # Create the PR
          gh pr create \
            --base main \
            --head dev \
            --title "Auto PR: $COMMIT_MSG" \
            --body "Automated PR from dev to main" \
            --label "automated-pr" || echo "PR might already exist or no changes to merge"
