# File: .github/workflows/pull-request.yml

on:
  push:
    branches:
    - dev

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: pull-request
    uses: nitesh2920/auto-pull-request@v1.0.1
      with:
      destination_branch: "main"
